name: Generate map tiles

on:
  push:
    branches: [ "**" ]
    paths: [ "*.dockerfile", "build/*", "*.github/workflows" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4
    - run: make tiles.vacant
    - run: make tiles.parking
    # TODO: re-enable after testing
    # - run: make tiles.all_lots

    - name: Create zip of pmtiles (parking and vacant)
      uses: actions/upload-artifact@v4
      with:
        name: emptynyc-tiles
        path: tiles/*.pmtiles
        if-no-files-found: error

    - id: auth
      uses: 'google-github-actions/auth@v3'
      continue-on-error: true # TODO: remove after testing
      with:
        project_id: 'empty-lots'
        workload_identity_provider: 'projects/415223443345/locations/global/workloadIdentityPools/github/providers/emptylots'

    - id: 'upload-files'
      uses: 'google-github-actions/upload-cloud-storage@v3'
      with:
        path: 'tiles'
        destination: 'nyc-lots-tiles/dev'
