name: Docker Image CI

on:
  push:
    branches: [ "**" ]
    paths: [ "*.dockerfile", "build/*" ]
  pull_request:
    branches: [ "**" ]
    paths: [ "*.dockerfile", "build/*" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the tippecanoe image
      run:  make create_image.tippecanoe
    - name: Build the gdal image with MapPLUTO dataset
      run:  make create_image.gdal
    - name: Push tippecanoe image
      run: push_image.tippecanoe
    - name: Push gdal image
      run: push_image.gdal
