name: Build and deploy static Frontend with Node.js

on:
  push:
    branches: [ "main" ]
    tags: [ "**" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GCP_BUCKET_WEB: ${{ vars.GCP_BUCKET_WEB }}
  GCP_PROJECT: ${{ vars.GCP_PROJECT }}
  GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  BRANCH: ${{ github.head_ref || github.ref_name }}
  IS_PREVIEW: ${{ github.ref_name != 'main' && github.ref_type != 'tag' }}

jobs:
  build:

    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'

    strategy:
      matrix:
        node-version: [25.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm audit --audit-level=moderate
    - run: make build.prod
      env:
        PUBLIC_URL: ${{ env.IS_PREVIEW == 'true' && './' || '/' }}
        TILE_CDN_URL: https://cdn.empty.nyc/${{ env.BRANCH }}
    - name: Create zip file of static production site
      uses: actions/upload-artifact@v4
      with:
        name: emptynyc-prod
        path: dist/**
        if-no-files-found: error

    - id: auth
      uses: 'google-github-actions/auth@v3'
      with:
        project_id: ${{ env.GCP_PROJECT }}
        workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}

    - id: 'upload-files'
      uses: 'google-github-actions/upload-cloud-storage@v3'
      with:
        path: 'dist'
        destination: ${{ env.GCP_BUCKET_WEB }}/${{ env.BRANCH }}
        parent: false # will not create a "dist" directory in the bucket
        project_id: ${{ env.GCP_PROJECT }}

    - name: Post preview URL to PR
      if: github.event_name == 'pull_request'
      uses: marocchino/sticky-pull-request-comment@v3
      with:
        header: preview-url
        message: |
          Preview: https://static.empty.nyc/${{ env.BRANCH }}
          (updated for commit ${{ github.event.pull_request.head.sha }})
